feat: Weapons Station
JDBryan/ZombieShooter pull request #32
Opened 2024-05-10 10:19 UTC by joachimboyden

Created a weapons station prefab (by default sells a shotgun) and a shotgun variant. 
Since there is no point system yet, I've made both the weapon and the ammo free for now. I've also made the ammo refill all your weapons ammo, but not the clip its self.

There are no Game Scene changes, so to test, just drag the prefab in. 
Also created a Interactable class, it currently only takes a radius of interaction and it's materials.

2024-05-19 20:06 UTC, JDBryan requested changes
If I buy a shotgun from the weapon station and then lose the shotgun by picking up another weapon, the weapon station will still only allow me to buy ammo rather than the expected behaviour of purchasing a weapon

2024-05-20 16:14 UTC, joachimboyden commented
Fixed your problem with dropping weapons and some other bugs I noticed. I also dragged the shotgun station into the game scene and deleted the shotgun that was on the ground.

2024-05-20 17:11 UTC, JDBryan commented on Assets/Scripts/Interactable.cs
> +    public void BaseStart(){
Rename function to Init

2024-05-20 17:25 UTC, JDBryan commented on Assets/Scripts/WeaponStation.cs
> +        if (this.weaponOnSale == false & this.restockInProgress == false){
Feels like you should maybe be using an else if here?

2024-05-20 17:26 UTC, JDBryan approved these changes
Approved with a couple of small comments

2024-05-22 08:59 UTC, merged