25 added enemy pathfinding
JDBryan/ZombieShooter pull request #6
Opened 2024-02-01 11:40 UTC by joachimboyden

Created pathfindingGrid class and pathfinder script.

Edited the enemy script very slightly to follow the pathfinder.

The only gameScene changes that need to stay are Obstacles having the Obstacle tag and the gameController having a new pathfinding component. If you spot ant others that I might have made, they can be overwritten.

2024-02-01 11:42 UTC, joachimboyden commented on Assets/Prefabs/Player.prefab
Don't remember touching the player prefab, probs just delete this change

2024-02-12 19:08 UTC, JDBryan requested changes

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/EnemyScript.cs
> +    private Pathfinger pathfinder;
Pathfinger -> pathfinder

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/EnemyScript.cs
> +        GetPathfinderTarget();
Use this.GetPathFinderTarget() just to follow a standard. Also, this is more personal preference but maybe consider removing the method altogether since it's just a one liner and is only used here.

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/PathfindingGrid.cs
> +    public PathfindingGrid(int width, int height, float cellSize, float X, float Y){
Don't use capital letters for the x and y variables here. Also maybe consider naming them something more descriptive, I'm not entirely sure what these represent

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/PathfindingGrid.cs
> +    public Vector2 GetLocalToWorldSpace(int x, int y){
If world space is using Vector3 then this should probably return a vector3. Also if this is doing what I think it's doing can you rename it to GetWorldSpaceFromCell. Also also, is it the case that function is only ever used in the GetCellCenter function below, if so I think you can just chuck this functionality into the GetCellCenter function and remove this

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/PathfindingGrid.cs
> +        Vector2 cell = GetCellFromWorldSpace(worldPosition);
Naming could do with some work here, if you called this something like originCell you can avoid using cel as a variable name in here.

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/PathfindingGrid.cs
> +    public Vector2 GetCellFromWorldSpace(Vector3 worldPosition){
Can you rename this to GetCellFromWorldPosition, I think replacing WorldSpace with WorldPosition makes sense everywhere else it's used as well.

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/PathfindingGrid.cs
> +    private bool DoesCellContainObsticle(int x, int y){
Obsticle -> Obstacle

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/PathfindingGrid.cs
> +        int colNum = Physics2D.OverlapBox(GetCellCenter(x,y), new Vector2(this.cellSize*0.9f,this.cellSize*0.9f), 0, new ContactFilter2D().NoFilter(), colliders);
Rename to colliderNumber

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/PathfindingGrid.cs
> +        if (colNum != 0){
Can remove this

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/PathfindingGrid.cs
> +                    containsObstacle = true;
can replace this with one line return true;

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/Pathfinger.cs
> +    private Queue<Vector2> frontier;
Remove frontier as a class scope variable here and add a comment describing what cameFrom is

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/Pathfinger.cs
> +    private Dictionary<Vector2,Vector2> BreadthFirstSearch(Vector2 start){
Rename start to target here

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/Pathfinger.cs
> +        Vector2 currentCell = Graph.GetClosestCell(startPosition);;
remove extra semicolon

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/Pathfinger.cs
> +    private void DebugPath(Vector3 position){
Remove this

2024-02-12 19:08 UTC, JDBryan commented on Assets/Scripts/Pathfinger.cs
> +    void Start()
Merge into PathfindingGrid

2024-03-10 17:40 UTC, JDBryan approved these changes
Just one minor change and then good to merge

2024-03-10 17:40 UTC, JDBryan commented on Assets/Scripts/PathfindingGrid.cs
> +        if (this.pathfindingGraph.ContainsKey(originCell) == false){
Small thing but this  `== false` is unnecessary as the `ContainsKey` method returns a boolean value so you can just use this directly by doing `!this.pathfindingGraph.ContainsKey(originCell)`

2024-03-13 15:56 UTC, merged